# Generated by Django 4.2.5 on 2023-09-28 15:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_user_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='User Name'),
            preserve_default=False,
        ),
    ]
