# Generated by Django 4.2.5 on 2023-10-02 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0007_animecollection_usersubscription_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_name',
        ),
    ]
