# Generated by Django 4.2.5 on 2023-10-02 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0009_user_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_name',
            new_name='username',
        ),
    ]
