# Generated by Django 4.2.5 on 2023-10-09 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0010_rename_user_name_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_img',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
