# Generated by Django 4.2.5 on 2023-09-28 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnimeList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('episodes', models.PositiveIntegerField()),
                ('image', models.CharField(max_length=500)),
                ('status', models.CharField(max_length=255)),
                ('synopsis', models.TextField()),
                ('type', models.CharField(max_length=255)),
                ('hasEpisode', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_number', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animeapp.animelist')),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode_number', models.PositiveIntegerField()),
                ('video_file', models.FileField(upload_to='episode_videos/')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animeapp.season')),
            ],
        ),
        migrations.AddField(
            model_name='animelist',
            name='gener',
            field=models.ManyToManyField(to='animeapp.genres'),
        ),
    ]
