# Generated by Django 4.2.5 on 2023-10-10 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animeapp', '0005_animerating_remove_animelist_num_ratings_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='animerating',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='animelist',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='animerating',
            name='anime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anime_ratings', to='animeapp.animelist'),
        ),
        migrations.AlterField(
            model_name='animerating',
            name='rating',
            field=models.PositiveIntegerField(choices=[(1, '1 - Awful'), (2, '2 - Poor'), (3, '3 - Average'), (4, '4 - Good'), (5, '5 - Excellent')]),
        ),
    ]
