# Generated by Django 4.2.5 on 2023-10-11 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animeapp', '0007_remove_animelist_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='animelist',
            name='rating',
            field=models.ManyToManyField(to='animeapp.animerating'),
        ),
    ]
