# Generated by Django 4.2.5 on 2023-10-11 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animeapp', '0010_animelist_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animerating',
            name='rating',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')]),
        ),
    ]
