# Generated by Django 4.2.5 on 2023-10-11 18:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('animeapp', '0011_alter_animerating_rating'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='animerating',
            unique_together={('user', 'anime')},
        ),
    ]
