# Generated by Django 4.2.5 on 2023-10-14 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animeapp', '0012_alter_animerating_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='animeapp.season'),
        ),
        migrations.AlterField(
            model_name='season',
            name='anime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='animeapp.animelist'),
        ),
    ]
